# Generated by Django 3.0.3 on 2020-07-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='org',
            name='state',
            field=models.CharField(default='Default', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='lastname',
            field=models.CharField(default='Lastname', max_length=256),
            preserve_default=False,
        ),
    ]
