# Generated by Django 3.0.3 on 2020-07-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200722_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='static/studysite/images/NoPho.jpg', upload_to=None),
        ),
    ]
