# Generated by Django 3.0.3 on 2020-07-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20200723_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='image',
            field=models.ImageField(default='NoPho.jpg', upload_to='images/'),
        ),
    ]
