# Generated by Django 3.0.3 on 2020-08-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_org_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studytitle', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=10000)),
                ('studyimage', models.ImageField(default='NoPho.jpg', upload_to='images/')),
                ('organisations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='info.Org')),
            ],
        ),
    ]
